export const inventoryData = [
  {
    _id: 1,
    name: "prod1",
    type: "type1",
    area: "Area3",
    location: "Loc1",
    quantity: 5,
  },
  {
    _id: 2,
    name: "prod2",
    type: "type2",
    area: "Area2",
    location: "Loc3",
    quantity: 3,
  },
  {
    _id: 3,
    name: "prod3",
    type: "type3",
    area: "Area1",
    location: "Loc4",
    quantity: 2,
  },
  {
    _id: 4,
    name: "prod4",
    type: "type1",
    area: "Area3",
    location: "Loc2",
    quantity: 6,
  },
  {
    _id: 5,
    name: "prod5",
    type: "type2",
    area: "Area4",
    location: "Loc5",
    quantity: 1,
  },
  {
    _id: 6,
    name: "prod6",
    type: "type3",
    area: "Area5",
    location: "Loc6",
    quantity: 7,
  },
  {
    _id: 7,
    name: "prod7",
    type: "type1",
    area: "Area2",
    location: "Loc1",
    quantity: 4,
  },
  {
    _id: 8,
    name: "prod8",
    type: "type2",
    area: "Area1",
    location: "Loc3",
    quantity: 9,
  },
  {
    _id: 9,
    name: "prod9",
    type: "type3",
    area: "Area4",
    location: "Loc2",
    quantity: 2,
  },
  {
    _id: 10,
    name: "prod10",
    type: "type1",
    area: "Area3",
    location: "Loc3",
    quantity: 3,
  },
  {
    _id: 11,
    name: "prod11",
    type: "type2",
    area: "Area2",
    location: "Loc2",
    quantity: 6,
  },
  {
    _id: 12,
    name: "prod12",
    type: "type3",
    area: "Area5",
    location: "Loc7",
    quantity: 4,
  },
  {
    _id: 13,
    name: "prod13",
    type: "type1",
    area: "Area1",
    location: "Loc1",
    quantity: 8,
  },
  {
    _id: 14,
    name: "prod14",
    type: "type2",
    area: "Area4",
    location: "Loc4",
    quantity: 1,
  },
  {
    _id: 15,
    name: "prod15",
    type: "type3",
    area: "Area3",
    location: "Loc4",
    quantity: 5,
  },
  {
    _id: 16,
    name: "prod16",
    type: "type1",
    area: "Area2",
    location: "Loc4",
    quantity: 7,
  },
  {
    _id: 17,
    name: "prod17",
    type: "type1",
    area: "Area3",
    location: "Loc5",
    quantity: 7,
  },
  {
    _id: 18,
    name: "prod18",
    type: "type4",
    area: "Area3",
    location: "Loc5",
    quantity: 3,
  },
];
